use std::io::{Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{self, Receiver, SyncSender, TryRecvError, TrySendError};
use std::sync::Arc;
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

use anyhow::{bail, Context, Result};
use portable_pty::{native_pty_system, Child, CommandBuilder, MasterPty, PtySize};

use crate::agent::{self, AgentKind, AgentState, AgentStatus};
use crate::info::{self, OscTracker, TabInfo};

const PTY_READ_CHUNK_BYTES: usize = 8 * 1024;
const PTY_QUEUE_CHUNKS: usize = 32;
const PTY_POLL_BYTE_BUDGET: usize = 32 * 1024;
/// Keystrokes/pastes are normally consumed immediately. A bounded asynchronous
/// queue prevents a child that stopped reading stdin from blocking every pane.
const PTY_INPUT_QUEUE_MESSAGES: usize = 256;

// Report a stable dark terminal palette to child applications. Components in
// xterm OSC color replies are 16-bit, hence the doubled 8-bit values.
const FOREGROUND_COLOR_REPLY: &[u8] = b"\x1b]10;rgb:bcbc/bcbc/bcbc\x1b\\";
const BACKGROUND_COLOR_REPLY: &[u8] = b"\x1b]11;rgb:1515/1515/1515\x1b\\";
const CURSOR_COLOR_REPLY: &[u8] = b"\x1b]12;rgb:bcbc/bcbc/bcbc\x1b\\";

fn child_terminal_environment() -> [(&'static str, &'static str); 2] {
    // Advertise only capabilities implemented by vt100 + mux's input encoder.
    // Inheriting xterm-kitty/alacritty would make child TUIs emit extensions
    // that the mux parser does not promise to support.
    [("TERM", "xterm-256color"), ("COLORTERM", "truecolor")]
}

/// Responses generated by terminal queries from a child TUI. They are sent
/// back through the child's PTY input, never forwarded to the host terminal.
#[derive(Debug, Default)]
struct TerminalCallbacks {
    responses: Vec<u8>,
}

impl TerminalCallbacks {
    fn take_responses(&mut self) -> Vec<u8> {
        std::mem::take(&mut self.responses)
    }

    fn single_param(params: &[&[u16]]) -> Option<u16> {
        match params {
            [] => Some(0),
            [[]] => Some(0),
            [param] if param.len() == 1 => param.first().copied(),
            _ => None,
        }
    }
}

impl vt100::Callbacks for TerminalCallbacks {
    fn unhandled_csi(
        &mut self,
        screen: &mut vt100::Screen,
        i1: Option<u8>,
        i2: Option<u8>,
        params: &[&[u16]],
        c: char,
    ) {
        let param = Self::single_param(params);
        match (i1, i2, c, param) {
            // ANSI device status report and cursor position report.
            (None, None, 'n', Some(5)) => {
                self.responses.extend_from_slice(b"\x1b[0n");
            }
            (None, None, 'n', Some(6)) => {
                let (row, col) = screen.cursor_position();
                self.responses
                    .extend_from_slice(format!("\x1b[{};{}R", row + 1, col + 1).as_bytes());
            }
            // Primary and secondary device attributes. The primary response
            // identifies a VT100 with advanced video; the secondary response
            // deliberately makes no invented firmware/version claim.
            (None, None, 'c', Some(0)) => {
                self.responses.extend_from_slice(b"\x1b[?1;2c");
            }
            (Some(b'>'), None, 'c', Some(0)) => {
                self.responses.extend_from_slice(b"\x1b[>0;0;0c");
            }
            _ => {}
        }
    }

    fn unhandled_osc(&mut self, _: &mut vt100::Screen, params: &[&[u8]]) {
        let response = match params {
            [b"10", b"?"] => Some(FOREGROUND_COLOR_REPLY),
            [b"11", b"?"] => Some(BACKGROUND_COLOR_REPLY),
            [b"12", b"?"] => Some(CURSOR_COLOR_REPLY),
            _ => None,
        };
        if let Some(response) = response {
            self.responses.extend_from_slice(response);
        }
    }
}

#[derive(Debug)]
enum PtyInput {
    User(Vec<u8>),
    Query(Vec<u8>),
}

/// The OS PTY input buffer can block indefinitely when a child stops reading.
/// Keep that wait off the UI/event-loop thread. `query_in_flight` stays set
/// until the corresponding write completes, bounding an infinite query flood
/// to one automatic response buffer plus the fixed-size input channel.
fn writer_loop(
    mut writer: Box<dyn Write + Send>,
    rx: Receiver<PtyInput>,
    query_in_flight: Arc<AtomicBool>,
) {
    while let Ok(input) = rx.recv() {
        let (bytes, is_query) = match input {
            PtyInput::User(bytes) => (bytes, false),
            PtyInput::Query(bytes) => (bytes, true),
        };
        let result = writer.write_all(&bytes).and_then(|_| writer.flush());
        if is_query {
            query_in_flight.store(false, Ordering::Release);
        }
        if result.is_err() {
            break;
        }
    }
    query_in_flight.store(false, Ordering::Release);
}

#[derive(Debug)]
struct PendingOutput {
    bytes: Vec<u8>,
    offset: usize,
}

#[derive(Debug, Default, PartialEq, Eq)]
struct DrainOutcome {
    bytes: usize,
    disconnected: bool,
}

/// Consume at most `budget` bytes while retaining the unconsumed tail of a
/// channel chunk. The reader channel is bounded, so stopping here propagates
/// backpressure through the PTY instead of growing memory without limit.
fn drain_output(
    rx: &Receiver<Vec<u8>>,
    pending: &mut Option<PendingOutput>,
    budget: usize,
    mut consume: impl FnMut(&[u8]),
) -> DrainOutcome {
    let mut outcome = DrainOutcome::default();

    while outcome.bytes < budget {
        if pending.is_none() {
            match rx.try_recv() {
                Ok(bytes) if !bytes.is_empty() => {
                    *pending = Some(PendingOutput { bytes, offset: 0 });
                }
                Ok(_) => continue,
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Disconnected) => {
                    outcome.disconnected = true;
                    break;
                }
            }
        }

        let Some(chunk) = pending.as_mut() else {
            continue;
        };
        let available = chunk.bytes.len() - chunk.offset;
        let take = available.min(budget - outcome.bytes);
        consume(&chunk.bytes[chunk.offset..chunk.offset + take]);
        chunk.offset += take;
        outcome.bytes += take;

        if chunk.offset == chunk.bytes.len() {
            *pending = None;
        }
    }

    outcome
}

/// One shell session: PTY + VT100 screen state + cmux-like metadata.
pub struct Tab {
    pub id: u64,
    /// OSC window title (raw).
    pub title: String,
    pub custom_title: bool,
    /// Live sidebar info (process + cwd).
    pub info: TabInfo,
    parser: vt100::Parser<TerminalCallbacks>,
    master: Box<dyn MasterPty + Send>,
    child: Box<dyn Child + Send + Sync>,
    input_tx: SyncSender<PtyInput>,
    query_in_flight: Arc<AtomicBool>,
    rx: Receiver<Vec<u8>>,
    pending_output: Option<PendingOutput>,
    _reader: JoinHandle<()>,
    _writer: JoinHandle<()>,
    child_exited: bool,
    reader_disconnected: bool,
    pub alive: bool,
    pub dirty: bool,
    shell_pid: Option<u32>,
    osc: OscTracker,
    cwd: Option<String>,
    process: Option<String>,
    last_probe: Instant,
    agent_kind: Option<AgentKind>,
    agent_state: Option<AgentState>,
    agent_title_revision: u64,
    last_output_at: Option<Instant>,
    last_agent_scan: Instant,
    cols: u16,
    rows: u16,
    /// Number of actual PTY bytes drained by the most recent poll.
    last_poll_bytes: usize,
}

impl Tab {
    pub fn spawn(id: u64, cols: u16, rows: u16) -> Result<Self> {
        let pty_system = native_pty_system();
        let pair = pty_system
            .openpty(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })
            .context("open pty")?;

        let shell = default_shell();
        let mut cmd = CommandBuilder::new(&shell);
        for (name, value) in child_terminal_environment() {
            cmd.env(name, value);
        }
        cmd.env("MUX", "1");
        cmd.env("MUX_TAB", id.to_string());

        if let Ok(cwd) = std::env::current_dir() {
            cmd.cwd(cwd);
        }

        let child = pair.slave.spawn_command(cmd).context("spawn shell")?;
        drop(pair.slave);

        let shell_pid = child.process_id();

        let mut reader = pair.master.try_clone_reader().context("clone pty reader")?;
        let writer = pair.master.take_writer().context("take pty writer")?;

        let query_in_flight = Arc::new(AtomicBool::new(false));
        let writer_query_in_flight = Arc::clone(&query_in_flight);
        let (input_tx, input_rx) = mpsc::sync_channel(PTY_INPUT_QUEUE_MESSAGES);
        let writer_handle = thread::Builder::new()
            .name(format!("mux-pty-write-{id}"))
            .spawn(move || writer_loop(writer, input_rx, writer_query_in_flight))
            .context("spawn pty writer thread")?;

        // A bounded queue caps userspace PTY buffering at roughly 256 KiB per
        // tab. When full, `send` blocks the reader and the kernel PTY applies
        // normal backpressure to a child producing output too quickly.
        let (tx, rx) = mpsc::sync_channel::<Vec<u8>>(PTY_QUEUE_CHUNKS);
        let reader_handle = thread::Builder::new()
            .name(format!("mux-pty-read-{id}"))
            .spawn(move || {
                let mut buf = [0u8; PTY_READ_CHUNK_BYTES];
                loop {
                    match reader.read(&mut buf) {
                        Ok(0) => break,
                        Ok(n) => {
                            if tx.send(buf[..n].to_vec()).is_err() {
                                break;
                            }
                        }
                        Err(err) => {
                            if err.kind() == std::io::ErrorKind::Interrupted {
                                continue;
                            }
                            if err.kind() == std::io::ErrorKind::WouldBlock {
                                thread::sleep(Duration::from_millis(2));
                                continue;
                            }
                            break;
                        }
                    }
                }
            })
            .context("spawn pty reader thread")?;

        let parser = vt100::Parser::new_with_callbacks(rows, cols, 0, TerminalCallbacks::default());

        let mut tab = Self {
            id,
            title: String::new(),
            custom_title: false,
            info: TabInfo {
                primary: "shell".into(),
                secondary: String::new(),
                agent: None,
            },
            parser,
            master: pair.master,
            child,
            input_tx,
            query_in_flight,
            rx,
            pending_output: None,
            _reader: reader_handle,
            _writer: writer_handle,
            child_exited: false,
            reader_disconnected: false,
            alive: true,
            dirty: true,
            shell_pid,
            osc: OscTracker::default(),
            cwd: None,
            process: None,
            last_probe: Instant::now() - Duration::from_secs(10),
            agent_kind: None,
            agent_state: None,
            agent_title_revision: 0,
            last_output_at: None,
            last_agent_scan: Instant::now() - Duration::from_secs(10),
            cols,
            rows,
            last_poll_bytes: 0,
        };
        tab.refresh_info(true);
        tab.refresh_agent_status(Instant::now(), true);
        tab.recompose();
        Ok(tab)
    }

    pub fn resize(&mut self, cols: u16, rows: u16) -> Result<()> {
        let cols = cols.max(1);
        let rows = rows.max(1);
        if self.cols == cols && self.rows == rows {
            return Ok(());
        }

        self.master
            .resize(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })
            .context("pty resize")?;
        self.parser.screen_mut().set_size(rows, cols);
        self.cols = cols;
        self.rows = rows;
        self.dirty = true;
        Ok(())
    }

    /// Drain pending PTY output into the VT parser. Returns true if anything changed.
    pub fn poll(&mut self) -> Result<bool> {
        let now = Instant::now();
        let mut changed = false;
        self.last_poll_bytes = 0;
        let outcome = drain_output(
            &self.rx,
            &mut self.pending_output,
            PTY_POLL_BYTE_BUDGET,
            |bytes| {
                self.osc.feed(bytes);
                self.parser.process(bytes);
            },
        );
        self.last_poll_bytes = outcome.bytes;

        let responses = self.parser.callbacks_mut().take_responses();
        if !responses.is_empty() {
            self.queue_query_response(responses);
        }

        if outcome.bytes > 0 {
            self.last_output_at = Some(now);
            changed = true;
            self.dirty = true;

            if !self.custom_title {
                if let Some(title) = self.osc.title.as_ref() {
                    if title != &self.title {
                        self.title.clone_from(title);
                    }
                }
            }
            if let Some(c) = self.osc.cwd.clone() {
                if self.cwd.as_ref() != Some(&c) {
                    self.cwd = Some(c);
                }
            }
        }
        if outcome.disconnected {
            self.reader_disconnected = true;
            self.alive = false;
        }

        // Refresh process/cwd from /proc a few times a second (cmux settles titles).
        let probed = self.last_probe.elapsed() >= Duration::from_millis(400);
        if probed {
            if self.refresh_info(false) {
                changed = true;
            }
        } else if changed {
            // Still recompose from OSC title/cwd without /proc scan.
            let prev = self.info.clone();
            self.recompose();
            if self.info != prev {
                changed = true;
            }
        }
        if self.refresh_agent_status(now, outcome.bytes > 0 || probed) {
            changed = true;
        }

        Ok(changed)
    }

    pub fn last_poll_bytes(&self) -> usize {
        self.last_poll_bytes
    }

    fn refresh_info(&mut self, force: bool) -> bool {
        self.last_probe = Instant::now();
        if let Some(pid) = self.shell_pid {
            #[cfg(unix)]
            let foreground_pgrp = self
                .master
                .process_group_leader()
                .and_then(|value| u32::try_from(value).ok());
            #[cfg(not(unix))]
            let foreground_pgrp = None;
            let (cwd, proc) = info::probe_session(pid, foreground_pgrp);
            if let Some(c) = cwd {
                // Prefer OSC 7 when present; /proc is fallback / cross-check.
                if self.osc.cwd.is_none() {
                    self.cwd = Some(c);
                } else if self.cwd.is_none() {
                    self.cwd = self.osc.cwd.clone();
                }
            } else if self.cwd.is_none() {
                self.cwd = self.osc.cwd.clone();
            }
            if let Some(p) = proc {
                self.process = Some(p);
            }
        }
        let prev = self.info.clone();
        self.recompose();
        force || self.info != prev
    }

    fn refresh_agent_status(&mut self, now: Instant, force: bool) -> bool {
        if !force && now.duration_since(self.last_agent_scan) < agent::SCAN_INTERVAL {
            return false;
        }
        self.last_agent_scan = now;

        let next_kind = self.process.as_deref().and_then(agent::identify_name);
        if next_kind != self.agent_kind {
            self.agent_kind = next_kind;
            self.agent_state = next_kind.map(|_| AgentState::Ready);
            // Ignore a title emitted by the previous foreground job. A newly
            // detected agent must publish another OSC title before it is used.
            self.agent_title_revision = self.osc.title_revision();
            self.recompose();
            return true;
        }

        let next_state = next_kind.map(|kind| {
            let title = if self.osc.title_revision() > self.agent_title_revision {
                self.osc.title.as_deref().unwrap_or_default()
            } else {
                ""
            };
            let quiet_for = self
                .last_output_at
                .map(|last| now.saturating_duration_since(last))
                .unwrap_or(Duration::MAX);
            agent::detect_state(kind, self.parser.screen(), title, quiet_for)
        });
        if next_state == self.agent_state {
            return false;
        }
        self.agent_state = next_state;
        self.recompose();
        true
    }

    fn recompose(&mut self) {
        // Keep OSC cwd authoritative when we have it.
        if let Some(c) = self.osc.cwd.clone() {
            self.cwd = Some(c);
        }
        let mut info = info::compose_info(
            &self.title,
            self.cwd.as_deref(),
            self.process.as_deref(),
            self.custom_title,
        );
        info.agent = self
            .agent_kind
            .zip(self.agent_state)
            .map(|(kind, state)| AgentStatus::single(kind, state));
        self.info = info;
    }

    pub fn write_all(&mut self, data: &[u8]) -> Result<()> {
        if !self.alive {
            bail!("tab {} is dead", self.id);
        }
        if data.is_empty() {
            return Ok(());
        }
        match self.input_tx.try_send(PtyInput::User(data.to_vec())) {
            Ok(()) => {}
            // Keep the event loop responsive under pathological stdin
            // backpressure. The queue already retains the previous 256 input
            // events in order; only the newest event is shed at the hard cap.
            Err(TrySendError::Full(_)) => {}
            Err(TrySendError::Disconnected(_)) => self.kill(),
        }
        Ok(())
    }

    fn queue_query_response(&mut self, response: Vec<u8>) {
        if self
            .query_in_flight
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        match self.input_tx.try_send(PtyInput::Query(response)) {
            Ok(()) => {}
            Err(TrySendError::Full(_)) => {
                self.query_in_flight.store(false, Ordering::Release);
            }
            Err(TrySendError::Disconnected(_)) => {
                self.query_in_flight.store(false, Ordering::Release);
                self.kill();
            }
        }
    }

    pub fn screen(&self) -> &vt100::Screen {
        self.parser.screen()
    }

    pub fn try_reap(&mut self) -> bool {
        if !self.child_exited {
            match self.child.try_wait() {
                Ok(Some(_)) => {
                    self.child_exited = true;
                    self.alive = false;
                }
                Ok(None) => {}
                Err(_) => {
                    self.child_exited = true;
                    self.alive = false;
                }
            }
        }

        // The process can exit before the reader has delivered its final
        // output. Keep the tab until EOF is observed after every queued byte
        // and pending chunk tail has been parsed.
        self.child_exited && self.reader_disconnected && self.pending_output.is_none()
    }

    pub fn kill(&mut self) {
        let _ = self.child.kill();
        self.alive = false;
    }
}

fn default_shell() -> String {
    std::env::var("SHELL").unwrap_or_else(|_| {
        if cfg!(target_os = "windows") {
            "powershell.exe".into()
        } else {
            "/bin/bash".into()
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    struct GateWriter {
        entered: SyncSender<()>,
        release: Option<Receiver<()>>,
    }

    impl Write for GateWriter {
        fn write(&mut self, bytes: &[u8]) -> std::io::Result<usize> {
            if let Some(release) = self.release.take() {
                self.entered.send(()).unwrap();
                release.recv().unwrap();
            }
            Ok(bytes.len())
        }

        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    #[test]
    fn drain_respects_budget_and_preserves_chunk_tail() {
        let (tx, rx) = mpsc::sync_channel(2);
        tx.send((0u8..10).collect()).unwrap();
        drop(tx);

        let mut pending = None;
        let mut output = Vec::new();
        let first = drain_output(&rx, &mut pending, 4, |bytes| {
            output.extend_from_slice(bytes)
        });
        assert_eq!(
            first,
            DrainOutcome {
                bytes: 4,
                disconnected: false
            }
        );
        assert!(pending.is_some());

        let second = drain_output(&rx, &mut pending, 4, |bytes| {
            output.extend_from_slice(bytes)
        });
        assert_eq!(
            second,
            DrainOutcome {
                bytes: 4,
                disconnected: false
            }
        );

        let third = drain_output(&rx, &mut pending, 4, |bytes| {
            output.extend_from_slice(bytes)
        });
        assert_eq!(
            third,
            DrainOutcome {
                bytes: 2,
                disconnected: true
            }
        );
        assert_eq!(output, (0u8..10).collect::<Vec<_>>());
    }

    #[test]
    fn bounded_output_channel_applies_backpressure() {
        let (tx, rx) = mpsc::sync_channel(1);
        tx.try_send(vec![1]).unwrap();
        assert!(matches!(tx.try_send(vec![2]), Err(TrySendError::Full(_))));
        assert_eq!(rx.recv().unwrap(), vec![1]);
        tx.try_send(vec![2]).unwrap();
        assert_eq!(rx.recv().unwrap(), vec![2]);
    }

    #[test]
    fn blocked_pty_writer_does_not_block_input_producers() {
        let (input_tx, input_rx) = mpsc::sync_channel(2);
        let (entered_tx, entered_rx) = mpsc::sync_channel(0);
        let (release_tx, release_rx) = mpsc::sync_channel(0);
        let query_in_flight = Arc::new(AtomicBool::new(true));
        let writer_query_in_flight = Arc::clone(&query_in_flight);
        let writer = thread::spawn(move || {
            writer_loop(
                Box::new(GateWriter {
                    entered: entered_tx,
                    release: Some(release_rx),
                }),
                input_rx,
                writer_query_in_flight,
            )
        });

        input_tx.try_send(PtyInput::Query(vec![1])).unwrap();
        entered_rx.recv_timeout(Duration::from_secs(1)).unwrap();

        // The writer is now deliberately blocked as an OS PTY write can be.
        // Producers still return immediately and stop at a fixed queue cap.
        input_tx.try_send(PtyInput::User(vec![2])).unwrap();
        input_tx.try_send(PtyInput::User(vec![3])).unwrap();
        assert!(matches!(
            input_tx.try_send(PtyInput::User(vec![4])),
            Err(TrySendError::Full(_))
        ));

        release_tx.send(()).unwrap();
        drop(input_tx);
        writer.join().unwrap();
        assert!(!query_in_flight.load(Ordering::Acquire));
    }

    #[test]
    fn budgeted_drains_do_not_lose_sustained_output() {
        let expected: Vec<u8> = (0..512 * 1024).map(|i| (i % 251) as u8).collect();
        let producer_bytes = expected.clone();
        let (tx, rx) = mpsc::sync_channel(2);
        let producer = thread::spawn(move || {
            for chunk in producer_bytes.chunks(PTY_READ_CHUNK_BYTES) {
                tx.send(chunk.to_vec()).unwrap();
            }
        });

        let mut pending = None;
        let mut actual = Vec::with_capacity(expected.len());
        loop {
            let outcome = drain_output(&rx, &mut pending, 997, |bytes| {
                actual.extend_from_slice(bytes)
            });
            assert!(outcome.bytes <= 997);
            if outcome.disconnected {
                break;
            }
            if outcome.bytes == 0 {
                thread::yield_now();
            }
        }

        producer.join().unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn child_terminal_capabilities_are_stable() {
        assert_eq!(
            child_terminal_environment(),
            [("TERM", "xterm-256color"), ("COLORTERM", "truecolor")]
        );
    }

    #[test]
    fn replies_to_dynamic_color_queries_without_forwarding_unknown_osc() {
        let mut parser = vt100::Parser::new_with_callbacks(24, 80, 0, TerminalCallbacks::default());
        parser.process(b"\x1b]10;?\x1b\\\x1b]11;?\x07\x1b]12;?\x1b\\");
        parser.process(b"\x1b]52;c;?\x1b\\\x1b]999;?\x1b\\");

        let mut expected = Vec::new();
        expected.extend_from_slice(FOREGROUND_COLOR_REPLY);
        expected.extend_from_slice(BACKGROUND_COLOR_REPLY);
        expected.extend_from_slice(CURSOR_COLOR_REPLY);
        assert_eq!(parser.callbacks_mut().take_responses(), expected);
    }

    #[test]
    fn replies_to_status_cursor_and_device_attribute_queries() {
        let mut parser = vt100::Parser::new_with_callbacks(24, 80, 0, TerminalCallbacks::default());
        parser.process(b"\x1b[3;4H\x1b[5n\x1b[6n\x1b[c\x1b[>c");

        assert_eq!(
            parser.callbacks_mut().take_responses(),
            b"\x1b[0n\x1b[3;4R\x1b[?1;2c\x1b[>0;0;0c"
        );
    }
}
